jobs:
  test:
    executor:
      name: node/default
      tag: "14.0"
    steps:
      - checkout
      - node/install-packages
      - run: npm run test

version: 2.1

orbs:
  node: circleci/node@2.0.3

workflows:
  test_my_app:
    jobs:
      - test
